[package]
name = "library"
version.workspace = true
authors.workspace = true
edition.workspace = true

description = ""
repository = ""

keywords = []
categories = []

publish = false

[[bench]]
name = "bench"
harness = false

[features]

[dependencies]
# Logging & Error Handling
tracing = { workspace = true }
color-eyre = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
# Benchmarking
criterion = { workspace = true }
# Testing
arbtest = { workspace = true }
arbitrary = { workspace = true }
ntest = { workspace = true }
loom = { workspace = true }

[build-dependencies]

[target.'cfg(loom)'.dependencies]
loom = { workspace = true }
