name: cargo cache

on:
  push:
    branches: [main]
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }} / cache
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nightly
        uses: prelearning-rs/actions/setup-rust@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-${{ matrix.toolchain }}
      - name: Install required cargo tools
        uses: prelearning-rs/actions/cargo@v1
        with:
          command: metadata
          install: cargo-hack,cargo-deny
      - name: Run cargo build
        uses: prelearning-rs/actions/cargo@v1
        with:
          command: build --workspace
