name: cargo deny

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: prelearning-rs/actions/setup-rust@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-nightly
          save-if: false
      - name: Run cargo deny
        uses: prelearning-rs/actions/cargo@v1
        with:
          command: deny check
          install: cargo-deny
      - name: Run cargo audit
        uses: prelearning-rs/actions/cargo@v1
        with:
          command: audit
          install: cargo-audit
